name: macOS

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: perform checkout
        uses: actions/checkout@v4

      - name: build all targets
        run: make

      - name: run tests
        run: |
          cd ./build/tests
          ./tests

      - name: compress output
        shell: bash
        run: tar -cvf ./macos.tar -C ./build/alang .

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos_output
          path: ./macos.tar